version: 2.1
jobs:
  dist:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build and upload to S3
          command: make dist
workflows:
  dist:
    jobs:
      - dist:
          filters:
            branches:
              only:
                - master
